version: 2.1
orbs:
  core: vanilla/core@2.1.0
aliases:
  - &attach_workspace
    attach_workspace:
      at: ~/workspace
  - &run_composer
    run:
      name: Install Composer Packages
      command: |
        cd ~/workspace/repo
        composer install --optimize-autoloader
jobs:
  php_setup:
    docker:
      - image: 'cimg/php:7.2'
    steps:
      - core/checkout
      # We explcitly don't cache dependencies.
      # The cache validation & fetching seems to take longer than fetching from source.
      - *run_composer
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - repo
  php_72_tests:
    docker:
      - image: 'cimg/php:7.2'
    steps: &php_unit_test_steps
      - *attach_workspace
      - run:
          name: Versions
          command: |
            php --version
            composer --version
      - run:
          name: PHPUnit Tests
          command: |
            cd ~/workspace/repo
            ./vendor/bin/phpunit -c ./tests/phpunit.xml.dist
  php_73_tests:
    docker:
      - image: 'cimg/php:7.3'
    steps: *php_unit_test_steps
  php_74_tests:
    docker:
      - image: 'cimg/php:7.4'
    steps: *php_unit_test_steps
  php_80_tests:
    docker:
      - image: 'cimg/php:8.0'
    steps: *php_unit_test_steps
  php_81_tests:
    docker:
      - image: 'cimg/php:8.1'
    steps: *php_unit_test_steps
workflows:
  version: 2
  commit:
    jobs:
      - php_setup
      - php_72_tests:
          requires:
            - php_setup
      - php_73_tests:
          requires:
            - php_setup
      - php_74_tests:
          requires:
            - php_setup
      - php_80_tests:
          requires:
            - php_setup
      - php_81_tests:
          requires:
            - php_setup
